type Product {
  id: ID!
  title: String!
  description: String!
  price: Float!
  rentPrice: Float
  rentOption: String
  createdAt: String!
  updatedAt: String!
  owner: User!
  categories: [Category!]!
  transactions: [Transaction!]!
}

extend type Query {
  allProducts: [Product!]!
  productById(id: ID!): Product
  myProducts: [Product!]!
}

input ProductInput {
  title: String!
  description: String!
  price: Float!
  rentPrice: Float
  rentOption: String
  categoryIds: [String!]
}

extend type Mutation {
  createProduct(input: ProductInput!): Product!
  updateProduct(id: ID!, input: ProductInput!): Product!
  deleteProduct(id: ID!): Boolean
}
