"""
Type of transaction: BUY or RENT
"""
enum TransactionType {
  BUY
  RENT
}

type Transaction {
  id: ID!
  type: TransactionType!
  createdAt: String!
  product: Product!
  user: User!
}

"""
Input type for creating a transaction (buy or rent)
"""
input CreateTransactionInput {
  productId: String!
  type: TransactionType!
}

extend type Mutation {
  """
  Create a transaction for a user to buy or rent a product.
  If type=BUY, the product is considered purchased.
  If type=RENT, the product is considered rented.
  """
  createTransaction(input: CreateTransactionInput!): Transaction!
}
